##############################
##                          ##
## EaseManage Configuration ##
##                          ##
##############################


# To indicate whether the command is enable or not
# Note that this setting is global 
# (i.e. All players cannot issue that command regardless of their permission)
# REQUIRED: bool

command-enable:
  serverstatus: true
  head: true
  spawn: true
  announcement: true
  stat: true
  backup: true
  
# Feature settings
# REQUIRED enable: bool
# REQUIRED WHEN ENABLE interval: int (seconds)

features:
  auto-message:
    enable: true
    interval: 180
    
# Color code for messages starts at '&', followed by the chat code indicator
# For more info, check https://www.digminecraft.com/lists/color_list_pc.php
# Note that we replace all '§' to '&'
# REQUIRED WHEN ENABLE: String
    msgs:
      - "&bTIPS: Use /spawn can back to your spawnpoint"
      - "&bTIPS: Use /stat can see your own statistics"
      - "&bTIPS: Use /serverstatus can check the current status of the server"

  auto-backup:
    enable: true
    interval: 7200
    
    # Max number of backups that you want to save in your disk
    # If the maximum number is reached, then EaseNabage will remove the 
    # oldest backup in your disk (Oldest creation date)
    # indicate -1 if you don't want to delete any backup
    # REQUIRED WHEN ENABLE: int
    max-backups: 10
    
    # Indicate which world(s) you want to perform backup
    # If it is blank, EaseManage will backup all active worlds
    # OPTIONAL: String
    
    #To be added as function
    #backup-worlds: []
    
  display-name:
    enable: true
    group:
    # List of an object
    # REQUIRED WHEN ENABLE
    # See the following example
    
      -
        prefix: "&c[EaseManage] "
        colorCode: "&d"
        playerNames: ["Oscar0713"]